services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - msa-network
    volumes:
      - ./postgres/:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: lenac115@naver.com
      PGADMIN_DEFAULT_PASSWORD: tmdhkzh77!
    networks:
      - msa-network

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - msa-network

networks:
  msa-network:
    external: true