services:
  postgres:
    image: postgres:15
    container_name: postgres
    command: [ "postgres", "-c", "max_connections=200" ]
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - msa-network
    volumes:
      - ./postgres/:/var/lib/postgresql/data

networks:
  msa-network:
    external: true