version: '3.8'
services:
  next-dev:
    image: nightwish115/front-service:latest
    container_name: front-service
    build:
      context: ./toss-pay-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./toss-pay-frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - msa-network

networks:
  msa-network:
    external: true