version: '3.8'
services:
  next-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next  # 개발 모드 캐시 유지
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - msa-network

networks:
  msa-network:
    external: true