services:
  zookeeper-local:
    container_name: zookeeper-local
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    networks:
      - msa-network

  kafka-local:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-local
    ports:
      - "9092:9092"    # for host (Spring)
      - "29092:29092"  # for other containers (Kafka UI)
    depends_on:
      - zookeeper-local
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-local:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,DOCKER://kafka-local:29092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,DOCKER://0.0.0.0:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - msa-network


  kafka-ui-local:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-local
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-local:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-local:2181
    networks:
      - msa-network
networks:
  msa-network:
    external: true