server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://${EC2_HOST}:8761/eureka
    fetch-registry: true
    register-with-eureka: false

spring:
  data:
    redis:
      host: redis
      port: 6379
      client-name: ${REDIS_USER}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      health-check:
        interval: 30s
        initial-delay: 15s
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - https://msa-prac.vercel.app
              - http://localhost:3000
              - https://msa-prac.duckdns.org
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
  main:
    web-application-type: reactive

  graphql:
    cors:
      allowed-origins: https://msa-prac.vercel.app, http://msa-prac.duckdns.org
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "Authorization, Content-Type"
      allow-credentials: true

front:
  uri: "https://msa-prac.vercel.app"

jwt:
  secret: ${JWT_SECRET}
