server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      client-name: root
      password: tmdhkzh77!
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: http://localhost:8083
          predicates:
            - Path=/payment/**
        - id: product-service
          uri: http://localhost:8084
          predicates:
            - Path=/product/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
  main:
    web-application-type: reactive

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "Authorization, Content-Type"

jwt:
  secret: "VlwEyVBsYt9V7zq57TejM223nVUyzb112lYcfPQye08f7MGVA9XkHa2233"
