server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    fetch-registry: true
    register-with-eureka: false

spring:
  data:
    redis:
      host: ${EC2_HOST_FRONT}
      port: 6379
      client-name: ${REDIS_USER}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      health-check:
        interval: 30s
        initial-delay: 15s
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
  main:
    web-application-type: reactive

  graphql:
    cors:
      allowed-origins: http://${EC2_HOST_FRONT}:3000
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "Authorization, Content-Type"

front:
  uri: http://${EC2_HOST_FRONT}:3000

jwt:
  secret: ${JWT_SECRET}
