spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${AZURE_HOST}:5432/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 60000
      max-lifetime: 1800000

  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true
    properties.hibernate.default_batch_fetch_size: 100
    open-in-view: true

  data:
    redis:
      host: redis
      port: 6379
      client-name: ${REDIS_USER}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8

  mail:
    host: smtp.gmail.com
    port: 587
    username: qndhkz115@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    password: ${MAIL_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8082
jwt:
  secret: ${JWT_SECRET}

eureka:
  instance:
    hostname: order-service
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
    ip-address: ${AZURE_HOST}
    instanceId: ${eureka.instance.hostname}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EC2_HOST}:8761/eureka