# fly.toml app configuration file generated for your-fly-postgres-app on 2025-07-16T14:03:26+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'your-fly-postgres-app'
primary_region = 'nrt'

[build]
  dockerfile = './Dockerfile'

[env]
  PGDATA = '/var/lib/postgresql/data'

[[mounts]]
  source = 'pg_data'
  destination = '/var/lib/postgresql/data'

[http_service]
  internal_port = 5432
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 5432

  [[services.ports]]
    port = 5432

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
