# fly.toml app configuration file generated for your-fly-postgres-app on 2025-07-16T22:29:09+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'your-fly-postgres-app'
primary_region = 'nrt'

[build]
  dockerfile = './Dockerfile'

[[mounts]]
  source = 'pg_data'
  destination = '/data'

[http_service]
  internal_port = 5432
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 5432

  [[services.ports]]
    port = 5432

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
