spring:
  application:
    name: auth
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: tmdhkzh77!

  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
    properties.hibernate.default_batch_fetch_size: 100
    open-in-view: true

  data:
    redis:
      host: localhost
      port: 6379
      client-name: root
      password: tmdhkzh77!
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8

  mail:
    host: smtp.gmail.com
    port: 587
    username: qndhkz115@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    password: tndhkzh7

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081
jwt:
  secret: "VlwEyVBsYt9V7zq57TejM223nVUyzb112lYcfPQye08f7MGVA9XkHa2233"