spring:
  application:
    name: discovery-server
server:
  port: 8761
eureka:
  instance:
    hostname: ${EC2_HOST}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    response-cache-update-interval-ms: 5000
    enable-self-preservation: false  # 테스트용으로 임시 비활성화 (프로덕션 X)
    eviction-interval-timer-in-ms: 10000
    renewal-percent-threshold: 0.85  # Renewal 임계값 (85%)

management.endpoints.web.exposure.include: "*"